name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: re1yun/knu-sublet-deploy
          stage: main
          yaml: >
            name: portfolio

            app: node@18

            options:
              env:
                - name: MONGO_URL
                  value: mongodb+srv://admin:DAxLf5bgI9z0PN0y@cluster0.qzsapze.mongodb.net/portfolio?retryWrites=true&w=majority
              ports: 3000
              start: npm run start
              install: npm ci
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
